"""
LEVEL 1 - add edge on static identifiers

Add edge for records that share a deterministic static ID like:
- serial number
- imei/meid
- mac address (although this has not been in the data we've seen so far)
- advertising fingerprint generated by the platform (e.g., facebook includes this)
- session id (accounting for redaction, see below)
"""
import pandas as pd
from utils.redaction_utils import compare_redacted_vals

DETERMINISTIC_KEYS = {
    "attr__device_id",
    "attr__device_serial_number",
    "attr__device_imei",
    "attr__device_meid",
    # we also merge on "attr__client_session_id", but with its own logic since this value is often partially redacted
}

IS_DETERMINISTIC_KEY = lambda k: any(k == dk or k.startswith(dk) for dk in DETERMINISTIC_KEYS)


def level1(df: pd.DataFrame) -> None:
    deterministic_cols = [df_col for df_col in df.columns if IS_DETERMINISTIC_KEY(df_col)] 
    melted = df[['id'] + deterministic_cols].melt(
        id_vars=['id'], 
        value_vars=deterministic_cols
    ).dropna()

    edges = melted.merge(
        melted,
        on=['value'],
        suffixes=('_a', '_b')
    )
    edges = edges[edges['id_a'] < edges['id_b']][['id_a', 'id_b']]
    edges['reason'] = 'level1_static_id__hardware'

    # then handle session id separately
    # Meta includes session ID data, but it is sometimes redacted like "ABCD*****". 
    # We want to link records with the same non-redacted substring, provided there is enough entropy in that substring.
    # Given that lestrade only works with one person's data, we declare that unredaced substrings must share at least 4 characters.
    # This is (2*26)^4 = a lot, and probably more sessions than any one user would have.
    # TODO --> could restrict to less than 1 year apart
    # See more in utils.redaction_utils
    session_id_col = 'attr__client_session_id'
    if session_id_col in df.columns:
        s_df = df[['id', session_id_col]].dropna()
        pairs = s_df.merge(s_df, how='cross', suffixes=('_a', '_b'))
        pairs = pairs[pairs['id_a'] < pairs['id_b']]
        matches = pairs.apply(
            lambda r: compare_redacted_vals(r[f'{session_id_col}_a'], r[f'{session_id_col}_b']),
            axis=1
        )
        edges = pd.concat([edges, pairs[matches][['id_a', 'id_b']]])
        edges['reason'] = 'level1_static_id__sessionid'

    return edges.drop_duplicates()